### ISSUE TITLE
Docker containers RabbitMQ integration?

### ISSUE THREAD

**Issue by sachinkariyattin** [airavata-courses/MethkupalliVasanth#10]
I see your commit on RabbitMQ https://github.com/airavata-courses/MethkupalliVasanth/commit/8b5e5484f6445594367713df91d5d289608753f5. But I dont see RabbitMQ being used in your code.

Also, you have not mentioned anything with respect to docker in your wiki. Are you still working on containerizing this?

**Comment by MethkupalliVasanth** [comment]
I have started working on rabbitmq couple of days back, and the commits are
in assignment-2 branch, regarding docker I tested it on contanerizing my
python microservice, will push the code soon.

**Comment by MethkupalliVasanth** [comment]
Have implemented the same. Working on Jetstream and Jenkins right now.

**Comment by sachinkariyattin** [comment]
Could you please update the wiki to test your docker containers?

**Comment by MethkupalliVasanth** [comment]
Please run the individual shell commands, it will set up the docker containers, you can test it at localhost:20000/rabbitmq, the reason for not updating the wiki is that I am currently working on testing the containers on jenkins which would then eliminate the testing of containers individually. So working on finishing the functionality.
