### ISSUE TITLE
No CICD pipeline has been implemented

### ISSUE THREAD

**Issue by eldhomathulla** [airavata-courses/MethkupalliVasanth#12]
Has not implemented a CI/CD pipeline for building deployment of your application using Jenkins

**Comment by MethkupalliVasanth** [comment]
Hi,

Have actually implemented that, and the Jenkins file be found.

**Comment by marpierc** [comment]
@MethkupalliVasanth Please resubmit with identified corrections.

**Comment by MethkupalliVasanth** [comment]
@eldhomathulla Made changes as suggested, the only take away is the logs which have the output of the microservices are served statically in the UI, have tried doing it dynamically, but couldn't, rest of it is implemented as suggested. Please verify.

Thanks
