### ISSUE TITLE
Unable to setup the database

### ISSUE THREAD

**Issue by neeraj-lad** [airavata-courses/MethkupalliVasanth#4]
I get the following error:
`... E QUERY    [thread1] SyntaxError: missing ; before statement @(shell):1:15`

You don't mention where I should be downloading the book.csv & genre.csv files. Maybe the error is because of missing files? I have already cloned your repo and I am running both mongod and the mongo shell inside the cloned directory.

**Comment by MethkupalliVasanth** [comment]
Have updated the instructions.
Thanks
