### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/MethkupalliVasanth#7]
All microservices are running fine.

There is a UI and a node.js Orchestrator / API Server, 
but the index.html has **redirect links** to the microservices.

```
<ul class="nav navbar-nav navbar-right">
            <li >
                 <a href="http://localhost:3000/api/books">Node js Microservice</a>
            </li>
</ul>
```

Instead, the expected workflow is 

1. UI invokes the API Server endpoint either synchronously or async using AJAX.
2. The API Server initiates requests to the microservices. 
3. Based on the responses from the microservices, the API Server displays data back to the UI.

The User should not be redirected away from the UI. A REST call is supposed to bring data back to the server. Thus, the API Server is not serving the purpose at the moment. 

Please implement an API server which acts as a gateway to the microservices. You could refer the [lecture slides](http://courses.airavata.org/slides/SICE-Fall17-B649-Assignment-1.pdf) for a better understanding.

**Comment by MethkupalliVasanth** [comment]
To address the above issues, have made changes to the orchestrator which invokes the API Server endpoint and displays back to the UI. Have made these changes in the 'new' branch. Please look into the server.js file and the index.html file, have made those changes.

However, my current implementation needs the user to open the index.html page inside the node.js orchestrator and this can be used as the UI to send the requests to the microservices. Please let me know if my implementation is right. Will update the readme, accordingly.

**Comment by Ameya05** [comment]
I would be review your assignment 1 today and let you know.

**Comment by Ameya05** [comment]
Working as expected, closing the issue!
